
stages:
  - prepare
  - lint
  - test

image: node:8

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./node_modules/

install:
  stage: prepare
  tags:
    - docker
  script:
    - npm install --unsafe-perm

lint:critical:
  stage: lint
  tags:
    - docker
  before_script:
  - npm install
  script:
    - npm run lint:critical

lint:
  stage: lint
  tags:
    - docker
  before_script:
  - npm install
  script:
    - npm run lint
  allow_failure: true

test:unit:
  stage: test
  tags:
    - docker
  services:
    - name: mongo:3.6
      alias: mongo
    - name: redis:4.0
      alias: redis
  before_script:
  - npm install
  script:
    - npm run test:unit

test:integration:
  stage: test
  tags:
    - docker
  services:
    - name: mongo:3.6
      alias: mongo
    - name: redis:4.0
      alias: redis
  before_script:
  - npm install
  script:
    - export MONGODB_URI=mongodb://mongo:27017/HelloWorldTest
    - export REDIS_URI=redis://redis:6379/10
    - npm run test:integration
