
stages:
  - lint
  - test

image: node:8

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./node_modules/

before_script:
 - npm install

lint:critical:
  stage: lint
  script:
    - npm run lint:critical

lint:
  stage: lint
  script:
    - npm run lint
  allow_failure: true

test:
  stage: test
  services:
    - name: mongo:3.6
      alias: mongo
    - name: redis:4.0
      alias: redis
  script:
    - npm run test
